apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice
  namespace: mungta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notice
  template:
    metadata:
      labels:
        app: notice
    spec:
      containers:
        - name: notice
          image: mungtaregistry.azurecr.io/mungta/dev/notice

---
apiVersion: v1
kind: Service
metadata:
  name: notice
  namespace: mungta
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: notice